name: Clocker CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: dart analyze

      - run: flutter config --enable-windows-desktop

      - name: Run tests
        run: flutter test

      - name: Build for Windows 
        run: flutter build windows

      - name: Generate version
        run: echo "::set-output name=version::$(Get-Date -Format 'yyyyMMdd')" 
        id: version

      - uses: actions/upload-artifact@v3
        with:
          name: clocker_${{steps.version.outputs.version}}
          path: ./build/windows/runner/Release

      - name: Generate release
        uses: actions/create-release@v1
        id: create_release
        with:
          release_name: clocker_${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
