name: Clocker CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: dart analyze

      - run: flutter config --enable-windows-desktop

      - name: Run tests
        run: flutter test

      - name: Build for Windows 
        run: flutter build windows

      - name: Generate version
        run: echo "::set-output name=version::$(Get-Date -Format 'yyyyMMdd')" 
        id: version

      - uses: actions/upload-artifact@v3
        run: echo "::set-output name=artifact_name::clocker_$(Get-Date -Format 'yyyyMMdd')" 
        with:
          name: clocker_${{steps.version.outputs.version}}.zip
          path: ./build/windows/runner/Release
        id: upload_artifact

      - name: Generate release
        uses: actions/create-release@v1
        id: create_release
        with:
          release_name: clocker_${{ steps.version.outputs.version }}.zip
          tag_name: ${{ github.ref }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ steps.upload_artifact.outputs.artifact_name }}
          asset_name: ${{ steps.upload_artifact.outputs.artifact_name }}
          asset_content_type: application/zip
