name: Clocker CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: dart analyze

      - run: flutter config --enable-windows-desktop

      - name: Run tests
        run: flutter test

      - name: Build for Windows 
        run: flutter build windows

      - name: Generate filename 
        run: echo "::set-output name=filename::clocker_$(Get-Date -Format 'yyyyMMdd')".zip
        id: filename

      - uses: actions/upload-artifact@v3
        with:
          name: ${{steps.finename.outputs.filename}}
          path: ./build/windows/runner/Release
        id: upload_artifact

      - name: Generate release
        uses: actions/create-release@v1
        id: create_release
        with:
          release_name: ${{ steps.filename.outputs.filename }}
          tag_name: ${{ steps.filename.outputs.filename }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Windows artifact
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ steps.filename.outputs.filename }}
          asset_name: ${{ steps.filename.outputs.filename }}
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
